app/models.py
from flask.ext.sqlalchemy import SQLAlchemy 
from flask.ext.login import LoginManager, UserMixin
from . import db, login_manager

class User(UserMixin, db.Model):
	__tablename__ = 'users'
	id = db.Column(db.Integer, primary_key=True)
	social_id = db.Column(db.String(64), nullable=False, unique=True)
	nickname = db.Column(db.String(64), nullable=False)
	email = db.Column(db.String(64), nullable=True)

@login_manager.user_loader
def load_user(id):
	return User.query.get(int(id))

app/__init__.py
from flask import Flask
from flask.ext.bootstrap import Bootstrap
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.login import LoginManager
from config import config

bootstrap = Bootstrap()
db = SQLAlchemy()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
login_manager.login_message = 'Please log in first!'

def create_app():
	app = Flask(__name__)
	app.config.from_object(config)
	config.init_app(app)

	bootstrap.init_app(app)
	db.init_app(app)
	login_manager.init_app(app)

	from .main import main as main_blueprint
	app.register_blueprint(main_blueprint)

	from .auth  import auth as auth_blueprint
	app.register_blueprint(auth_blueprint, url_prefix='/auth')

	return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
from flask import render_template
from . import main


@main.route('/')
def index():
    return render_template('index.html')

@main.route('/archives/')
def archives():
    return render_template('archives.html')

@main.route('/about/')
def about():
    return render_template('about.html')

@main.route('/resume/')
def resume():
    return render_template('resume.html')

app/templates/about.html
{% extends "base.html" %}

app/templates/archives.html
{% extends "base.html" %}


<!-- <h1>Hello World!</h1> -->

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}周凯{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='zhoukai.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='zhoukai.ico') }}" type="image/x-icon">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='mystyles.css') }}">
{% endblock %}

{% block navbar %}
<nav class="navbar navbar-default">
	<div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
		    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		    </button>
		    <a class="navbar-brand" href="{{ url_for('main.index') }}">周凯</a>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	    	<ul class="nav navbar-nav">
		        <li class="active"><a href="{{ url_for('main.index') }}">首页 <span class="sr-only">(current)</span></a></li>
		        <li><a href="{{ url_for('main.archives') }}">存档</a></li>
		        <li><a href="{{ url_for('main.about') }}">关于</a></li>
	    	</ul>
	    	<form class="navbar-form navbar-left" role="search">
		        <div class="form-group">
		          <input type="text" class="form-control" placeholder="搜索|暂不可用">
		        </div>
		        <button type="submit" class="btn btn-default">Submit</button>
	    	</form>
	    	<ul class="nav navbar-nav navbar-right">
		        <li>
		        	<p class="navbar-text" style="margin-top: 10px; margin-bottom: 0px;">
			            <a type="application/rss+xml" href="/feed"><img src="/static/rss.png" alt="RSS Feed" title="RSS Feed" /></a>
			            <a href="http://github.com/zhoukaigo/"><img src="/static/github.png" alt="GitHub" title="GitHub" /></a>
			            <a href="http://weibo.com/u/2446719565/"><img src="/static/weibo.png" alt="Facebook" title="Facebook" /></a>
		        	</p>
		        </li>
	    	</ul>
	    </div><!-- /.navbar-collapse -->
	</div><!-- /.container-fluid -->
</nav>
{% endblock %}

{% block content %}
<div class="main-part">
	<div class="row">
		<div class="col-md-8">
			<div class="col-md-8">
				<h1>文章文章文章文章文章文章文章文章文章文章</h1>
		
			<div class="col-md-4">
				{% include 'sidebar.html' %} 
			</div>
		</div>
	</div>	
</div>

{% endblock %}

<!-- <h1>Hello World!</h1> -->

app/templates/essay_thumbs.html
<h1>文章文章文章文章文章文章文章文章文章文章</h1>
<h1>文章文章文章文章文章文章文章文章文章文章</h1>
<h1>文章文章文章文章文章文章文章文章文章文章</h1>
<h1>文章文章文章文章文章文章文章文章文章文章</h1>
<h1>文章文章文章文章文章文章文章文章文章文章</h1>
<h1>文章文章文章文章文章文章文章文章文章文章</h1>
<h1>文章文章文章文章文章文章文章文章文章文章</h1>
<h1>文章文章文章文章文章文章文章文章文章文章</h1>
<h1>文章文章文章文章文章文章文章文章文章文章</h1>
<h1>文章文章文章文章文章文章文章文章文章文章</h1>
<h1>文章文章文章文章文章文章文章文章文章文章</h1>
<h1>文章文章文章文章文章文章文章文章文章文章</h1>
<h1>文章文章文章文章文章文章文章文章文章文章</h1>

app/templates/footer.html
<footer>
	<p>周凯-勇敢的心</p>
</footer>

app/templates/index.html
{% extends "mybase.html" %}

{% block content %}
	<div class="container-fluid">
		<div class="row">
			<div class="col-xs-12 col-sm-8 main-part">
				{% include 'essay_thumbs.html' %}
			</div>
			<div class="col-xs-12 col-sm-4 sidebar">
				{% include 'sidebar.html' %}
			</div>
		</div>
	</div>
	{% include 'footer.html' %}
{% endblock %}

app/templates/mybase.html
{% block doc -%}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>周凯</title>
		<link rel="icon" href="{{ url_for('static', filename='zhoukai.ico') }}" type="image/x-icon">

		{%- block styles %}
			<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='mystyles.css') }}">
			<link href="{{bootstrap_find_resource('css/bootstrap.css', cdn='bootstrap')}}" rel="stylesheet">
			<!-- 以下两个插件用于在IE8以及以下版本浏览器支持HTML5元素和媒体查询，如果不需要用可以移除 -->
	        <!--[if lt IE 9]>
	        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
	        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
	        <![endif]-->
		{%- endblock styles %}
	</head>
<body>
	{% block body -%}
		{% include 'nav.html' %} 

		{% block content -%}

		{% endblock content -%}

		{% block scripts %}
			<script src="{{bootstrap_find_resource('jquery.js', cdn='jquery')}}"></script>
	    	<script src="{{bootstrap_find_resource('js/bootstrap.js', cdn='bootstrap')}}"></script>	
		{% endblock scripts %}
	{% endblock body -%}
</body>
</html>
{% endblock doc -%}
<!-- Bootstrap不支持IE的兼容模式，这行代码是为了在IE中运行最新的渲染模式 -->

app/templates/nav.html
<nav class="navbar navbar-default">
	<div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
		    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		    </button>
		    <a class="navbar-brand" href="{{ url_for('main.resume') }}">周凯</a>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	    	<ul class="nav navbar-nav">
		        <li class="active"><a href="{{ url_for('main.index') }}">首页 <span class="sr-only">(current)</span></a></li>
		        <li><a href="{{ url_for('main.archives') }}">存档</a></li>
		        <li><a href="{{ url_for('main.about') }}">关于</a></li>
	    	</ul>
	    	<form class="navbar-form navbar-left" role="search">
		        <div class="form-group">
		          <input type="text" class="form-control" placeholder="搜索|暂不可用">
		        </div>
		        <button type="submit" class="btn btn-default">Submit</button>
	    	</form>
	    	<ul class="nav navbar-nav navbar-right">
		        <li>
		        	<p class="navbar-text" style="margin-top: 10px; margin-bottom: 0px;">
			            <a type="application/rss+xml" href="/feed"><img src="/static/rss.png" alt="RSS Feed" title="RSS Feed" /></a>
			            <a href="http://github.com/zhoukaigo/"><img src="/static/github.png" alt="GitHub" title="GitHub" /></a>
			            <a href="http://weibo.com/u/2446719565/"><img src="/static/weibo.png" alt="Facebook" title="Facebook" /></a>
		        	</p>
		        </li>
	    	</ul>
	    </div><!-- /.navbar-collapse -->
	</div><!-- /.container-fluid -->
</nav>

app/templates/resume.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>周凯的简历</title>
    <link rel="icon" href="{{ url_for('static', filename='zhoukai.ico') }}" type="image/x-icon">
    <link rel="stylesheet" href="{{ url_for('static', filename='resume.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/remodal/1.1.0/remodal.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/remodal/1.1.0/remodal-default-theme.min.css">
</head>

<body>
    <div class="container" id="cv">
        <div class="side">
            <div class="me">
                <div class="portrait" style="background-image: url('../static/blue.jpg');">
                </div>
                <h1 id="username" >周凯</h1>
                <!-- <h4 id="persona-tag" >Python / Web / 互联网教育</h4> -->
            </div>
            <div class="profile info-unit">
                <h2 class="info-header"><i class="iconfont icon-person"></i> <span class="info-title">基本信息</span></h2>
                <hr>
                <ul class="info-list">
                    <li>
                        <label class="left-label">姓名</label><span class="label-value">周凯</span></li>
                    <li>
                        <label class="left-label">学历</label><span class="label-value">硕士</span></li>
                    <li>
                        <label class="left-label">毕业院校</label><span class="label-value">西安交通大学</span></li>
                    <li>
                        <label class="left-label">毕业年份</label><span class="label-value">2017</span></li>
                </ul>
            </div>
            <div class="contact info-unit">
                <h2 class="info-header"><i class="iconfont icon-call"></i> <span class="info-title">联系方式</span></h2>
                <hr>
                <ul class="info-list">
                    <li>
                        <label class="left-label">手机</label><span class="label-value">182-9287-7064</span></li>
                    <li>
                        <label class="left-label">邮箱</label><span class="label-value">zhoukaigo@qq.com</span></li>
                    <li>
                        <label class="left-label">个人主页</label><span class="label-value">zhoukaigo.com</span></li>
                    <li>
                        <label class="left-label">Github</label><span class="label-value">github.com/zhoukaigo</span></li>
                </ul>
            </div>
            <div class="stack info-unit">
                <h2 class="info-header"><i class="iconfont icon-build"></i> <span class="info-title">技能点</span></h2>
                <hr>
                <div id="left">
                <ul class="stack-list">
                    <li>AutoCAD</li>
                    <li>Solidworks</li>
                    <li>Pro/Engineer</li>
                    <li>Unigraphics NX</li>
                    <li>COMSOL</li>
                    <li>ABAQUS</li>
                    <li>Multisim</li>

                </ul>
                </div>
                <div id="right">
                <ul class="stack-list">
                    <li>Python</li>
                    <li>MATLAB</li>
                    <li>Git</li>
                    <li>HTTP</li>
                    <li>HTML/CSS</li>
                    <li>JavaScript</li>
                    <li>OriginLab</li>
                </ul>
                </div>
            </div>

            <div class="code info-unit">
                <h2 class="info-header"><i class="iconfont icon-weixin"></i> <span class="info-title">个人微信</span></h2>
                <hr>
                <div class="weixin">
                    <img src="{{ url_for('static', filename='weixin.jpg') }}" alt="">

                </div>
            </div>
        </div>
        <div class="main">
            <div class="education info-unit right-list">
                <h2 class="info-header"><i class="iconfont icon-education"></i> <span class="info-title">教育经历</span></h2>
                <hr>
                <ul class="experience-list">
                    <li>
                        <h3>西安交通大学 - 机械制造（硕士）2014-2017</h3>
                    </li>
                    <li>
                        <h3>哈尔滨工业大学 - 机械设计制造及其自动化（本科）2010-2014</h3>
                    </li>
                </ul>
            </div>
            <div class="work info-unit right-list">
                <h2 class="info-header"><i class="iconfont icon-work"></i> <span class="info-title">实习经历</span></h2>
                <hr>
                <ul class="experience-list">
                    <li>
                        <h3>苏州陈那自动化</h3>
                        <p>
                            完成气浮轴承和气浮主轴的设计、装配及调试，完成多孔质石墨轴瓦的加工。
                        </p>
                    </li>
                    <li>
                        <h3>北京龙创光学机械有限公司</h3>
                        <p>完成玻璃环的铣磨和抛光以及相关砂轮、夹具的设计。
                        </p>
                    </li>
                    <li>
                        <h3>长春一汽</h3>
                    </li>
                    <li>
                        <h3>哈尔滨汽轮机厂，哈尔滨量具刃具厂，哈尔滨电机厂，哈尔滨轴承集团</h3>
                    </li>
                </ul class="experience-list">
            </div>
            <div class="project info-unit right-list">
                <h2 class="info-header"><i class="iconfont icon-project"></i> <span class="info-title">个人项目</span></h2>
                <hr>
                <ul class="experience-list">
                    <li>
                        <h3>气浮轴承及气浮主轴的研发</h3>
                        <p>
                            该项目以高端制造装备中的高精气体轴承支撑主轴为典型研究对象，对多孔质气浮轴承的理论分析、气浮主轴的设计及优化、气浮主轴的性能试验进行研究。其中我完成的工作有：气浮轴承的设计及其装配，并在此基础上完成气浮主轴的设计，同时完成多孔质石墨轴瓦的加工制造。
                            <br/>
                        </p>
                    </li>
                    <li>
                        <h3>玻璃环的铣磨及其抛光</h3>
                        <p>
                            该玻璃环除了有尺寸要求外，还有严格的形位公差要求，同时要求抛光并达到相应的光学要求。其中我完成的工作有：制定加工工艺，完成玻璃环的铣磨、抛光及相关砂轮、夹具的设计。采用内孔和外环同时抛光的工艺，使抛光速度大大提高。
                        </p>
                    </li>
                </ul>
            </div>
            <div class="trophy info-unit">
                <h2 class="info-header"><i class="iconfont icon-trophy"></i> <span class="info-title">奖项与证书</span></h2>
                <hr>
                <ul class="experience-list">
                    <li>
                        <h3>全国大学生数学竞赛黑龙江赛区一等奖</h3>
<!--                         <p>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam。
                        </p> -->
                    </li>
                    <li>
                        <h3>哈尔滨工业大学人民奖学金（三等）</h3>
<!--                         <p>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam。
                        </p> -->
                    </li>
                    <li>
                        <h3>英语四级（592）, 英语六级（514）</h3>
<!--                         <p>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam。
                        </p> -->
                    </li>
<!--                     <li>
                        <h3>曾获统一冰红茶“再来一瓶”奖</h3>
                        <p>
                            "再来一瓶"奖中奖概率很低, 是一个很重要的奖
                        </p>
                    </li>   -->
            </div>
            <div class="trophy info-unit">
                <h2 class="info-header"><i class="iconfont icon-star"></i> <span class="info-title">社会活动</span></h2>
                <hr>
                <ul class="experience-list">
                    <li>
                        <h3>西安浐灞石佛寺小学支教（2015）</h3>
                    </li>
                    <li>
                        <h3>关爱小动物之救治流浪狗（2013）</h3>
                    </li>
                    <li>
                        <h3>创建学院图书室（2012）</h3>
                    </li>
                    <li>
                        <h3>学雷锋之清洁社区（2012）</h3>
                    </li>
                    <li>
                        <h3>绿协之植树活动（2011）</h3>
                    </li>
            </div>
            <div class="aboutme info-unit right-paragraph">
                <h2 class="info-header"><i class="iconfont icon-flower"></i> <span class="info-title">自我评价</span></h2>
                <hr>
                <ul class="rate-list">
                    <li>
                        <h3>逻辑思维能力强，数理功底扎实，曾获大学生数学竞赛黑龙江赛区一等奖。</h3>
                    </li>
                    <li>
                        <h3>专业基础扎实，成绩排名中上；实践能力强，在北京龙创、陈那自动化等公司实习将近一年。</h3>
                    </li>
                    <li>
                        <h3>热爱新鲜事物，勇于改变，敢于尝试，本硕先后就读于哈工大和西安交大；自学编程，独立建立个人网站zhoukaigo.com。</h3>
                    </li>
                    <li>
                        <h3>富有责任心，勇于承担责任，多次利用业余时间参加社会活动。创建学院图书室，方便同学在公寓学习；参加支教活动，带给孩子们不一样的学习体验。</h3>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</body>

</html>

app/templates/sidebar.html
<div class="sidebar">
	<div class="aboutme">
		<h1>关于我</h1><hr/>
		<p>大家好，我是周凯。我这个是我的个人博客，参照Miguelgrinberg的教程、用python+flask写的。希望能在这里和大家互相学习交流</p>
	</div>
	<div class="Other">
		<h1>其他</h1><hr/>
		<P>这里是其他内容，待补充。谢谢关注！</P>
	</div>
</div>